const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923184474176";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "true"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",

  sessionName:process.env.SESSION_ID || "SUHAIL_12_23_09_01_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgOCxcbiAgICAgICAgMTM3LFxuICAgICAgICA3NCxcbiAgICAgICAgODEsXG4gICAgICAgIDM3LFxuICAgICAgICAxMTEsXG4gICAgICAgIDIyMCxcbiAgICAgICAgMTY0LFxuICAgICAgICAxMSxcbiAgICAgICAgMCxcbiAgICAgICAgMjIxLFxuICAgICAgICAxNjcsXG4gICAgICAgIDQ1LFxuICAgICAgICAxMTcsXG4gICAgICAgIDE2MyxcbiAgICAgICAgNzAsXG4gICAgICAgIDg5LFxuICAgICAgICAyMTYsXG4gICAgICAgIDEzNixcbiAgICAgICAgMTA4LFxuICAgICAgICA0NCxcbiAgICAgICAgMjUzLFxuICAgICAgICAzOSxcbiAgICAgICAgMTIsXG4gICAgICAgIDI3LFxuICAgICAgICAyMDYsXG4gICAgICAgIDEzNCxcbiAgICAgICAgMjIwLFxuICAgICAgICAyOSxcbiAgICAgICAgMjI4LFxuICAgICAgICA1NSxcbiAgICAgICAgNzRcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTQ5LFxuICAgICAgICAxMDIsXG4gICAgICAgIDEwMSxcbiAgICAgICAgMTk0LFxuICAgICAgICAyOSxcbiAgICAgICAgMjE3LFxuICAgICAgICAxMzMsXG4gICAgICAgIDIxMCxcbiAgICAgICAgMTM2LFxuICAgICAgICAxMDEsXG4gICAgICAgIDgyLFxuICAgICAgICAxMjIsXG4gICAgICAgIDkzLFxuICAgICAgICA3MCxcbiAgICAgICAgMTc2LFxuICAgICAgICAxNDMsXG4gICAgICAgIDE3NyxcbiAgICAgICAgMjI5LFxuICAgICAgICAzNixcbiAgICAgICAgMjEsXG4gICAgICAgIDE1OCxcbiAgICAgICAgNDMsXG4gICAgICAgIDE1NyxcbiAgICAgICAgNTgsXG4gICAgICAgIDE1NyxcbiAgICAgICAgNjMsXG4gICAgICAgIDIzMSxcbiAgICAgICAgMjM4LFxuICAgICAgICAxOTIsXG4gICAgICAgIDI0MyxcbiAgICAgICAgMTIxLFxuICAgICAgICA2MlxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJwYWlyaW5nRXBoZW1lcmFsS2V5UGFpclwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTIwLFxuICAgICAgICAyMSxcbiAgICAgICAgMTAyLFxuICAgICAgICAzLFxuICAgICAgICAxOTMsXG4gICAgICAgIDEzMyxcbiAgICAgICAgMTY2LFxuICAgICAgICAyNDksXG4gICAgICAgIDk1LFxuICAgICAgICAzLFxuICAgICAgICAyNSxcbiAgICAgICAgNDQsXG4gICAgICAgIDQxLFxuICAgICAgICAxODEsXG4gICAgICAgIDg4LFxuICAgICAgICAyMjMsXG4gICAgICAgIDIyNCxcbiAgICAgICAgMjA1LFxuICAgICAgICA3NixcbiAgICAgICAgMTY3LFxuICAgICAgICAyNDQsXG4gICAgICAgIDcwLFxuICAgICAgICA5NSxcbiAgICAgICAgMjgsXG4gICAgICAgIDE4MCxcbiAgICAgICAgNTYsXG4gICAgICAgIDcsXG4gICAgICAgIDI1MCxcbiAgICAgICAgMTAsXG4gICAgICAgIDI1LFxuICAgICAgICAxODYsXG4gICAgICAgIDY1XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE2LFxuICAgICAgICAxMTgsXG4gICAgICAgIDEzNixcbiAgICAgICAgMzksXG4gICAgICAgIDE5MixcbiAgICAgICAgNixcbiAgICAgICAgNjksXG4gICAgICAgIDE2NyxcbiAgICAgICAgMTgsXG4gICAgICAgIDIxNSxcbiAgICAgICAgMTU4LFxuICAgICAgICA1MyxcbiAgICAgICAgMTU5LFxuICAgICAgICAxMTEsXG4gICAgICAgIDM4LFxuICAgICAgICAyMDgsXG4gICAgICAgIDI2LFxuICAgICAgICA3MyxcbiAgICAgICAgNjIsXG4gICAgICAgIDI1LFxuICAgICAgICAxNDIsXG4gICAgICAgIDUzLFxuICAgICAgICAxOTgsXG4gICAgICAgIDE2NyxcbiAgICAgICAgNSxcbiAgICAgICAgMTczLFxuICAgICAgICA4NSxcbiAgICAgICAgMTQzLFxuICAgICAgICAyNTIsXG4gICAgICAgIDE5NixcbiAgICAgICAgMTEzLFxuICAgICAgICAyNVxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRJZGVudGl0eUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTUyLFxuICAgICAgICAxMDAsXG4gICAgICAgIDkzLFxuICAgICAgICAxNjMsXG4gICAgICAgIDc3LFxuICAgICAgICAxNjcsXG4gICAgICAgIDc1LFxuICAgICAgICAyMDUsXG4gICAgICAgIDI2LFxuICAgICAgICA2NyxcbiAgICAgICAgNTUsXG4gICAgICAgIDg3LFxuICAgICAgICA3NyxcbiAgICAgICAgMTYwLFxuICAgICAgICAxMzUsXG4gICAgICAgIDExMCxcbiAgICAgICAgMjU1LFxuICAgICAgICAyNDgsXG4gICAgICAgIDEyOCxcbiAgICAgICAgMjEsXG4gICAgICAgIDY3LFxuICAgICAgICAxODIsXG4gICAgICAgIDE0OCxcbiAgICAgICAgMjA0LFxuICAgICAgICAxODksXG4gICAgICAgIDczLFxuICAgICAgICAxNDIsXG4gICAgICAgIDExMixcbiAgICAgICAgMzUsXG4gICAgICAgIDE5LFxuICAgICAgICA4NyxcbiAgICAgICAgNzBcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTAsXG4gICAgICAgIDM2LFxuICAgICAgICA3NCxcbiAgICAgICAgNTksXG4gICAgICAgIDIxMCxcbiAgICAgICAgMzEsXG4gICAgICAgIDcyLFxuICAgICAgICA1MixcbiAgICAgICAgMTMxLFxuICAgICAgICAxMDIsXG4gICAgICAgIDI3LFxuICAgICAgICAyMTcsXG4gICAgICAgIDUxLFxuICAgICAgICAxOTgsXG4gICAgICAgIDE0MixcbiAgICAgICAgODgsXG4gICAgICAgIDE2LFxuICAgICAgICAyMzEsXG4gICAgICAgIDY3LFxuICAgICAgICAxNixcbiAgICAgICAgMTg2LFxuICAgICAgICAxOCxcbiAgICAgICAgMTU4LFxuICAgICAgICA3MCxcbiAgICAgICAgODksXG4gICAgICAgIDkwLFxuICAgICAgICAyMzUsXG4gICAgICAgIDEzNyxcbiAgICAgICAgMTcyLFxuICAgICAgICA2MCxcbiAgICAgICAgMTI1LFxuICAgICAgICAxMTdcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkUHJlS2V5XCI6IHtcbiAgICBcImtleVBhaXJcIjoge1xuICAgICAgXCJwcml2YXRlXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMjE2LFxuICAgICAgICAgIDE4NCxcbiAgICAgICAgICAxMjMsXG4gICAgICAgICAgNzksXG4gICAgICAgICAgMjgsXG4gICAgICAgICAgMjQyLFxuICAgICAgICAgIDIxLFxuICAgICAgICAgIDE5MSxcbiAgICAgICAgICA1MSxcbiAgICAgICAgICAxMzAsXG4gICAgICAgICAgMTM1LFxuICAgICAgICAgIDE4MixcbiAgICAgICAgICAxODgsXG4gICAgICAgICAgMjQ4LFxuICAgICAgICAgIDExMCxcbiAgICAgICAgICAxMDYsXG4gICAgICAgICAgMTk1LFxuICAgICAgICAgIDc5LFxuICAgICAgICAgIDIwNCxcbiAgICAgICAgICA4LFxuICAgICAgICAgIDIyMSxcbiAgICAgICAgICA5MixcbiAgICAgICAgICAyMjMsXG4gICAgICAgICAgMTk4LFxuICAgICAgICAgIDIxOSxcbiAgICAgICAgICAxNDMsXG4gICAgICAgICAgMTEsXG4gICAgICAgICAgMTMzLFxuICAgICAgICAgIDE4NSxcbiAgICAgICAgICA4MixcbiAgICAgICAgICA3NCxcbiAgICAgICAgICAxMDRcbiAgICAgICAgXVxuICAgICAgfSxcbiAgICAgIFwicHVibGljXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMzQsXG4gICAgICAgICAgMjUsXG4gICAgICAgICAgMjIxLFxuICAgICAgICAgIDEzNCxcbiAgICAgICAgICA0MyxcbiAgICAgICAgICA4NCxcbiAgICAgICAgICAyMyxcbiAgICAgICAgICAxOTcsXG4gICAgICAgICAgMTkzLFxuICAgICAgICAgIDc3LFxuICAgICAgICAgIDEyLFxuICAgICAgICAgIDE1NixcbiAgICAgICAgICAzMyxcbiAgICAgICAgICAxOTYsXG4gICAgICAgICAgMjM5LFxuICAgICAgICAgIDIxMyxcbiAgICAgICAgICA3MyxcbiAgICAgICAgICA3MSxcbiAgICAgICAgICAyNTIsXG4gICAgICAgICAgNTcsXG4gICAgICAgICAgNDQsXG4gICAgICAgICAgMTk4LFxuICAgICAgICAgIDIwMixcbiAgICAgICAgICAxMjQsXG4gICAgICAgICAgNjUsXG4gICAgICAgICAgMjEyLFxuICAgICAgICAgIDIxNyxcbiAgICAgICAgICAyNTMsXG4gICAgICAgICAgNDYsXG4gICAgICAgICAgMjQ0LFxuICAgICAgICAgIDU3LFxuICAgICAgICAgIDY2XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9LFxuICAgIFwic2lnbmF0dXJlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTUyLFxuICAgICAgICAyMzQsXG4gICAgICAgIDEyNyxcbiAgICAgICAgNjUsXG4gICAgICAgIDE5LFxuICAgICAgICAxOTMsXG4gICAgICAgIDM5LFxuICAgICAgICA1OCxcbiAgICAgICAgNjYsXG4gICAgICAgIDMxLFxuICAgICAgICA2NyxcbiAgICAgICAgMjUsXG4gICAgICAgIDE3NSxcbiAgICAgICAgMTM0LFxuICAgICAgICAxNTEsXG4gICAgICAgIDM3LFxuICAgICAgICAxMTUsXG4gICAgICAgIDE3NCxcbiAgICAgICAgMTIsXG4gICAgICAgIDEwNyxcbiAgICAgICAgMixcbiAgICAgICAgMTQ2LFxuICAgICAgICAyMzksXG4gICAgICAgIDEyNSxcbiAgICAgICAgMTE2LFxuICAgICAgICAxMzUsXG4gICAgICAgIDE3NyxcbiAgICAgICAgMjMsXG4gICAgICAgIDI0NSxcbiAgICAgICAgMTgsXG4gICAgICAgIDIxOSxcbiAgICAgICAgMjQwLFxuICAgICAgICAxNCxcbiAgICAgICAgMjUyLFxuICAgICAgICAzMSxcbiAgICAgICAgMTQ5LFxuICAgICAgICAxOTUsXG4gICAgICAgIDYxLFxuICAgICAgICAyMjcsXG4gICAgICAgIDE2OSxcbiAgICAgICAgNjUsXG4gICAgICAgIDg4LFxuICAgICAgICA2MCxcbiAgICAgICAgMTAxLFxuICAgICAgICAxMzUsXG4gICAgICAgIDE4NSxcbiAgICAgICAgMjAsXG4gICAgICAgIDEwOCxcbiAgICAgICAgMTI1LFxuICAgICAgICAxMzEsXG4gICAgICAgIDIzMSxcbiAgICAgICAgMjQwLFxuICAgICAgICAxMzgsXG4gICAgICAgIDE1NCxcbiAgICAgICAgMTMsXG4gICAgICAgIDE2LFxuICAgICAgICAxOTAsXG4gICAgICAgIDk2LFxuICAgICAgICAxNjYsXG4gICAgICAgIDE0NyxcbiAgICAgICAgMjU1LFxuICAgICAgICA5NSxcbiAgICAgICAgMTAxLFxuICAgICAgICAzXG4gICAgICBdXG4gICAgfSxcbiAgICBcImtleUlkXCI6IDFcbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25JZFwiOiAxMzMsXG4gIFwiYWR2U2VjcmV0S2V5XCI6IFwiS1dCRytKUi9FUDU1Q3NuVlo0c1RpNnpmZGFLQW1FWG4xMkd6M0NXanViaz1cIixcbiAgXCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXNcIjogW1xuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCI5MjMwNTUwNTQ3NTVAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIjdBMDM4QzU2NjQ2QTc3OEQwMzI5QTlFMDNCNzUxRTZGXCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcyNTE5MzQyN1xuICAgIH0sXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjkyMzA1NTA1NDc1NUBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiMzEzOEU5OTAwNzJFNTIwMkI4Mzc2QkVGNjEyNjc3RTdcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzI1MTkzNDI5XG4gICAgfVxuICBdLFxuICBcIm5leHRQcmVLZXlJZFwiOiAzMSxcbiAgXCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZFwiOiAzMSxcbiAgXCJhY2NvdW50U3luY0NvdW50ZXJcIjogMSxcbiAgXCJhY2NvdW50U2V0dGluZ3NcIjoge1xuICAgIFwidW5hcmNoaXZlQ2hhdHNcIjogZmFsc2VcbiAgfSxcbiAgXCJkZXZpY2VJZFwiOiBcInlzOW9xb054UzFhQy16MDFpdlBxdGdcIixcbiAgXCJwaG9uZUlkXCI6IFwiZjFlNjA0ZDktNzU2ZS00MjhjLThjMmItZjk3M2JhODQ2OGJmXCIsXG4gIFwiaWRlbnRpdHlJZFwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDEyOCxcbiAgICAgIDg3LFxuICAgICAgMTY1LFxuICAgICAgMjQxLFxuICAgICAgMTkxLFxuICAgICAgMTMxLFxuICAgICAgMjM4LFxuICAgICAgMzQsXG4gICAgICAxMjEsXG4gICAgICA0MixcbiAgICAgIDE2MCxcbiAgICAgIDY0LFxuICAgICAgMjA0LFxuICAgICAgMjM0LFxuICAgICAgNTYsXG4gICAgICAyNDgsXG4gICAgICAyMTQsXG4gICAgICAxNjIsXG4gICAgICAxLFxuICAgICAgMTE3XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdGVyZWRcIjogdHJ1ZSxcbiAgXCJiYWNrdXBUb2tlblwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDE4MixcbiAgICAgIDUsXG4gICAgICA4MixcbiAgICAgIDUxLFxuICAgICAgMTg2LFxuICAgICAgMjMzLFxuICAgICAgNjQsXG4gICAgICAxNTksXG4gICAgICAxMzMsXG4gICAgICA2MCxcbiAgICAgIDIwNixcbiAgICAgIDQ5LFxuICAgICAgMTIxLFxuICAgICAgMTQwLFxuICAgICAgMTQ3LFxuICAgICAgMTM3LFxuICAgICAgNTAsXG4gICAgICAxMzUsXG4gICAgICA0NSxcbiAgICAgIDMwXG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJwYWlyaW5nQ29kZVwiOiBcIkI4SkJEQkdZXCIsXG4gIFwibWVcIjoge1xuICAgIFwiaWRcIjogXCI5MjMwNTUwNTQ3NTU6MTVAcy53aGF0c2FwcC5uZXRcIixcbiAgICBcImxpZFwiOiBcIjcyMTUxNzI2MDYzODUyOjE1QGxpZFwiLFxuICAgIFwibmFtZVwiOiBcIllPVVIgREFEIPCfmIJcIlxuICB9LFxuICBcImFjY291bnRcIjoge1xuICAgIFwiZGV0YWlsc1wiOiBcIkNMV2U5TThIRU11NTBiWUdHQUVnQUNnQVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZUtleVwiOiBcImsxYWd3aEJsb3pxSnZTaU1pVm84K0ZEOVZaTmZSM21Ob0o0bzhJTiswWFU9XCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlXCI6IFwiU3ZlSGRIV0F3S3lkOE1mbDdxQTJFd2t1em1SM1FkdUZoTDZ6RGZPMy92K1hoMlNibk1TSmFaMElGZFp3TEFHeVlUNkNyeDlPTG9rOE5FcVFucm5IQWc9PVwiLFxuICAgIFwiZGV2aWNlU2lnbmF0dXJlXCI6IFwiZEwxbHdBeXVwT3hKRHRGQVd1M1M0ZlNpejRicDU4cHJ2b082ektUTWYzYmt4ZUVzb3c5RlcxbVRQclE1MUVQQTlBcTNYcW5BcWptcTZESytlL3hWRHc9PVwiXG4gIH0sXG4gIFwic2lnbmFsSWRlbnRpdGllc1wiOiBbXG4gICAge1xuICAgICAgXCJpZGVudGlmaWVyXCI6IHtcbiAgICAgICAgXCJuYW1lXCI6IFwiOTIzMDU1MDU0NzU1OjE1QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZGV2aWNlSWRcIjogMFxuICAgICAgfSxcbiAgICAgIFwiaWRlbnRpZmllcktleVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDUsXG4gICAgICAgICAgMTQ3LFxuICAgICAgICAgIDg2LFxuICAgICAgICAgIDE2MCxcbiAgICAgICAgICAxOTQsXG4gICAgICAgICAgMTYsXG4gICAgICAgICAgMTAxLFxuICAgICAgICAgIDE2MyxcbiAgICAgICAgICA1OCxcbiAgICAgICAgICAxMzcsXG4gICAgICAgICAgMTg5LFxuICAgICAgICAgIDQwLFxuICAgICAgICAgIDE0MCxcbiAgICAgICAgICAxMzcsXG4gICAgICAgICAgOTAsXG4gICAgICAgICAgNjAsXG4gICAgICAgICAgMjQ4LFxuICAgICAgICAgIDgwLFxuICAgICAgICAgIDI1MyxcbiAgICAgICAgICA4NSxcbiAgICAgICAgICAxNDcsXG4gICAgICAgICAgOTUsXG4gICAgICAgICAgNzEsXG4gICAgICAgICAgMTIxLFxuICAgICAgICAgIDE0MSxcbiAgICAgICAgICAxNjAsXG4gICAgICAgICAgMTU4LFxuICAgICAgICAgIDQwLFxuICAgICAgICAgIDI0MCxcbiAgICAgICAgICAxMzEsXG4gICAgICAgICAgMTI2LFxuICAgICAgICAgIDIwOSxcbiAgICAgICAgICAxMTdcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH1cbiAgXSxcbiAgXCJwbGF0Zm9ybVwiOiBcImFuZHJvaWRcIixcbiAgXCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXBcIjogMTcyNTE5MzQyMyxcbiAgXCJteUFwcFN0YXRlS2V5SWRcIjogXCJBQUFBQU5MVVwiXG59IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBTkxVLmpzb24iOiAie1wia2V5RGF0YVwiOlwiVnVtb2lZZjRnazdYQXFsWnE4eHpQb0hyNW9uTmFGdjBURlo2TUE1YU1UWT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoyMDQ2NjI3NjM3LFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjE3MjUxOTM0MjY5NDNcIn0iCn0=",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
